Repository pokeclicker/pokeclicker, pull requests merged in 2020-10, with the labels that each got.

#831 Allow users to view their eggs and fossils even when they cannot use …
  src/components/breeding.html
  src/styles/breeding.less
Labels: improvement

#869 fix(lint): adds Radix argument to all calls to parseInt
  src/components/shopModal.html
  src/scripts/items/ItemHandler.ts
  src/scripts/pokedex/PokedexHelper.ts
  src/scripts/settings/Settings.ts
  src/scripts/shop/ShopHandler.ts
  src/scripts/underground/Underground.ts
Labels: improvement

#873 Bulk buys -- configurable shop buttons
  src/components/settingsModal.html
  src/components/shopModal.html
  src/scripts/settings/Settings.ts
  src/scripts/shop/ShopHandler.ts
  src/scripts/towns/Town.ts
Labels: improvement, user interface

#887 Make eggs all fit on one line when in middle column
  src/styles/breeding.less
Labels: improvement, user interface

#888 Fixup the link to images for Pokémon on the dynamic background
  src/scripts/DynamicBackground.ts
Labels: bug, user interface

#880 Makes Oak Item popover display levels consistently
  src/scripts/oakItems/OakItem.ts
Labels: improvement, user interface

#835 chore(circular): moves notification constants into separate file
  src/components/settingsModal.html
  src/scripts/App.ts
  src/scripts/Game.ts
  src/scripts/GameConstants.ts
  src/scripts/NotificationConstants.ts
  src/scripts/Notifier.ts
  src/scripts/Save.ts
  src/scripts/Update.ts
  src/scripts/achievements/Achievement.ts
  src/scripts/battleFrontier/BattleFrontier.ts
  src/scripts/battleFrontier/BattleFrontierMilestones.ts
  src/scripts/battleFrontier/BattleFrontierRunner.ts
  src/scripts/breeding/Breeding.ts
  src/scripts/breeding/BreedingController.ts
  src/scripts/breeding/Egg.ts
  src/scripts/codes/RedeemableCode.ts
  src/scripts/codes/RedeemableCodes.ts
  src/scripts/discord/Discord.ts
  src/scripts/discord/DiscordCode.ts
  src/scripts/discord/DiscordPokemonCode.ts
  src/scripts/dungeons/Dungeon.ts
  src/scripts/dungeons/DungeonRunner.ts
  src/scripts/effectEngine/effectEngineRunner.ts
  src/scripts/farming/FarmController.ts
  src/scripts/farming/Farming.ts
  src/scripts/gym/GymRunner.ts
  src/scripts/items/EnergyRestore.ts
  src/scripts/items/Item.ts
  src/scripts/items/ItemHandler.ts
  src/scripts/items/PokemonItem.ts
  src/scripts/party/Party.ts
  src/scripts/party/evolutions/Evolution.ts
  src/scripts/pokemons/BattlePokemon.ts
  src/scripts/pokemons/PokemonFactory.ts
  src/scripts/quests/Quest.ts
  src/scripts/quests/QuestLineHelper.ts
  src/scripts/quests/Quests.ts
  src/scripts/safari/Safari.ts
  src/scripts/safari/SafariPokemon.ts
  src/scripts/settings/Settings.ts
  src/scripts/shards/Shards.ts
  src/scripts/specialEvents/SpecialEvent.ts
  src/scripts/underground/Mine.ts
  src/scripts/underground/Underground.ts
  src/scripts/upgrades/Upgrade.ts
  src/scripts/worldmap/MapHelper.ts
Labels: improvement

#904 chore: recommend `npm ci` over `npm i` for exact dependencies
  .travis.yml
  README.md
Labels: dependencies

#836 chore(circular): move BadgeTypes into separate file
  src/components/badgeCase.html
  src/components/receiveGymBadge.html
  src/scripts/achievements/GymBadgeRequirement.ts
  src/scripts/badgeCase/BadgeCase.ts
  src/scripts/badgeCase/BadgeCaseController.ts
  src/scripts/badgeCase/BadgeTypes.ts
  src/scripts/dungeons/Dungeon.ts
  src/scripts/gym/Champion.ts
  src/scripts/gym/Gym.ts
  src/scripts/gym/GymRunner.ts
  src/scripts/pokemons/RoamingPokemonList.ts
  src/scripts/towns/Town.ts
  src/scripts/wildBattle/Routes.ts
Labels: improvement

#909 Update Pokemon shop images
  src/assets/images/items/Beldum.png
  src/assets/images/items/Burmy_(plant).png
  src/assets/images/items/Cherubi.png
  src/assets/images/items/Combee.png
  src/assets/images/items/Eevee.png
  src/assets/images/items/Jynx.png
  src/assets/images/items/Lickitung.png
  src/assets/images/items/Mr._Mime.png
  src/assets/images/items/Porygon.png
  src/assets/images/items/Skorupi.png
  src/assets/images/items/Spiritomb.png
  src/assets/images/items/Togepi.png
Labels: improvement, user interface

#894 feat(breeding): adds setting to control egg hatching animation
  src/components/breedingDisplay.html
  src/components/settingsModal.html
  src/scripts/breeding/BreedingController.ts
  src/scripts/settings/Settings.ts
Labels: improvement, user interface

#871 TypeScript modules
  .gitignore
  .travis.yml
  gulpfile.babel.js
  package-lock.json
  package.json
  src/components/shortcutsContainer.html
  src/index.html
  src/modules/DataStore/BadgeStore.ts
  src/modules/DataStore/StatisticStore.ts
  src/modules/DataStore/common/Feature.ts
  src/modules/DataStore/common/Saveable.ts
  src/modules/DataStore/index.ts
  src/modules/GameConstants.ts
  src/modules/index.ts
  src/modules/temporaryWindowInjection.ts
  src/scripts/GameConstants.ts
  src/scripts/achievements/AchievementHandler.ts
  src/scripts/badgeCase/BadgeCaseController.ts
  src/scripts/breeding/Breeding.ts
  src/scripts/codes/RedeemableCodes.ts
  src/scripts/dungeons/DungeonRunner.ts
  src/scripts/gym/Gym.ts
  src/scripts/gym/GymRunner.ts
  src/scripts/index.ts
  src/scripts/pokemons/RoamingPokemonList.ts
  src/scripts/quests/QuestLineHelper.ts
  src/scripts/quests/questTypes/DefeatDungeonQuest.ts
  src/scripts/quests/questTypes/DefeatGymQuest.ts
  src/scripts/towns/PokemonLeague.ts
  src/scripts/towns/Town.ts
  src/scripts/wildBattle/Routes.ts
  src/scripts/worldmap/MapHelper.ts
  tsconfig.json
  tsconfigWithModules.json
  webpack.config.js
Labels: discussion, improvement

#917 chore: Add a few NPCs to give tips on how to get some pokemon in game
  src/scripts/towns/Town.ts
Labels: improvement

#883 Update Achievement Tracker Display
  src/scripts/achievements/AchievementHandler.ts
  src/styles/achievement.less
Labels: bug, improvement, user interface

#872 Pokeball Selector Modal
  src/components/pokeballSelector.html
  src/components/pokeballSelectorModal.html
  src/index.html
  src/scripts/pokeballs/Pokeball.ts
  src/scripts/pokeballs/Pokeballs.ts
Labels: discussion, improvement, user interface

#923 fix(notification): level the gain of sounds to match
  src/assets/sounds/achievement.mp3
  src/assets/sounds/battle_item_timer.mp3
  src/assets/sounds/new_catch.mp3
  src/assets/sounds/quest_level_increased.mp3
  src/assets/sounds/quest_ready_to_complete.mp3
  src/assets/sounds/ready_to_harvest.mp3
  src/assets/sounds/ready_to_hatch.mp3
  src/assets/sounds/shiny_long.mp3
  src/assets/sounds/underground_energy_full.mp3
Labels: improvement

#906 feat(achievements): adds buttons to jump to first and last pages
  src/assets/images/arrow-double.svg
  src/assets/images/arrow.svg
  src/assets/images/leftarrow.png
  src/assets/images/rightarrow.png
  src/components/achievementsModal.html
  src/scripts/achievements/AchievementHandler.ts
Labels: improvement, user interface

#862 Save Mine as part of Underground
  src/scripts/Game.ts
  src/scripts/Save.ts
  src/scripts/underground/Mine.ts
  src/scripts/underground/Underground.ts
Labels: improvement

#931 Check if egg hatched before replacing the egg
  src/scripts/breeding/Breeding.ts
  src/scripts/breeding/Egg.ts
Labels: bug

#919 TypeScript Modules linting
  gulpfile.babel.js
  package-lock.json
  package.json
  src/components/badgeCase.html
  src/components/receiveGymBadge.html
  src/modules/.eslintrc.js
  src/modules/DataStore/BadgeCase.ts
  src/modules/DataStore/BadgeStore.ts
  src/modules/DataStore/StatisticStore.ts
  src/modules/DataStore/index.ts
  src/modules/GameConstants.ts
  src/modules/enums/Badges.ts
  src/modules/index.ts
  src/modules/koExtenders.d.ts
  src/modules/koExtenders.ts
  src/modules/temporaryWindowInjection.ts
  src/modules/utilities/getArrayOfObservables.ts
  src/scripts/App.ts
  src/scripts/ArrayOfObservables.ts
  src/scripts/Game.ts
  src/scripts/GameConstants.d.ts
  src/scripts/GameConstants.ts
  src/scripts/achievements/GymBadgeRequirement.ts
  src/scripts/badgeCase/BadgeCaseController.ts
  src/scripts/dungeons/Dungeon.ts
  src/scripts/farming/Farming.ts
  src/scripts/gym/Champion.ts
  src/scripts/gym/Gym.ts
  src/scripts/gym/GymRunner.ts
  src/scripts/index.ts
  src/scripts/pokemons/PokemonHelper.ts
  src/scripts/pokemons/PokemonList.ts
  src/scripts/pokemons/RoamingPokemonList.ts
  src/scripts/shards/Shards.ts
  src/scripts/towns/Town.ts
  src/scripts/wallet/AmountFactory.ts
  src/scripts/wallet/Wallet.ts
  src/scripts/wildBattle/Routes.ts
Labels: improvement

#912 feat(battle): pokemon attack tooltip shows actual attack against enemy
  src/index.html
  src/scripts/gym/GymRunner.ts
Labels: improvement, user interface

#948 Fix: Remove getArrayOfObservables
  src/components/breedingDisplay.html
  src/components/farmModal.html
  src/components/questModal.html
  src/components/shardsModal.html
  src/components/shopModal.html
  src/components/townView.html
  src/components/underground.html
  src/index.html
  src/modules/DataStore/BadgeCase.ts
  src/modules/temporaryWindowInjection.ts
  src/modules/utilities/getArrayOfObservables.ts
  src/scripts/farming/Farming.ts
  src/scripts/shards/Shards.ts
  src/scripts/wallet/Wallet.ts
Labels: bug

#971 fix(statistics): fix bug with porting old or early-region saves
  src/modules/DataStore/StatisticStore/index.ts
  src/scripts/Update.ts
Labels: bug

#961 fix(party): rework party list layout to fit in small layouts
  src/components/pokemonListContainer.html
  src/index.html
  src/styles/main.less
Labels: improvement

#1007 fix(statistics): Fix bug with length property
  src/modules/DataStore/StatisticStore/index.ts
Labels: bug
